name: "Code Analysis"

on:
  push:
    paths:
      - "web/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "web/**"
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  analyze:
    name: Analyze
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@main

    - name: Setup CodeQL
      uses: github/codeql-action/init@main
      with:
        languages: ${{ matrix.language }}
    - name: Perform Analysis
      uses: github/codeql-action/analyze@main
      with:
        category: "/language:${{matrix.language}}"
