name: "Deploy web"

on:
  push:
    paths:
      - "web/**"
    branches: ["main"]
  pull_request:
    paths:
      - "web/**"
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: pnpm/action-setup@master
        name: Setup pnpm
        with:
          version: latest
          run_install: false

      - name: Get path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@main
        name: Check pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-web-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-web-pnpm-store-
      - name: Check web cache
        uses: actions/cache@main
        with:
          path: |
            web/.next/cache
          key: ${{ runner.os }}-web-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-web-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install deps
        run: pnpm i --frozen-lockfile
      - name: Build web
        run: pnpm build
      - name: Deploy web
        uses: cloudflare/pages-action@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: onewhim
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: web
          wranglerVersion: "beta"
